name: Docker CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Login
        env: # Or as an environment variable
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:  docker login docker.pkg.github.com -u msalgados -p $DOCKER_PASSWORD
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile Java with Gradle
        run: ./gradlew -Pprod bootJar jib
